<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class MunicipalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipalities = [
            ['name' => 'Abalá', 'state_id' => 1],
            ['name' => 'Acanceh', 'state_id' => 1],
            ['name' => 'Akil', 'state_id' => 1],
            ['name' => 'Baca', 'state_id' => 1],
            ['name' => 'Bokobá', 'state_id' => 1],
            ['name' => 'Buctzotz', 'state_id' => 1],
            ['name' => 'Cacalchén', 'state_id' => 1],
            ['name' => 'Calotmul', 'state_id' => 1],
            ['name' => 'Cansahcab', 'state_id' => 1],
            ['name' => 'Cantamayec', 'state_id' => 1],
            ['name' => 'Celestún', 'state_id' => 1],
            ['name' => 'Cenotillo', 'state_id' => 1],
            ['name' => 'Chacsinkín', 'state_id' => 1],
            ['name' => 'Chankom', 'state_id' => 1],
            ['name' => 'Chapab', 'state_id' => 1],
            ['name' => 'Chemax', 'state_id' => 1],
            ['name' => 'Chicxulub Pueblo', 'state_id' => 1],
            ['name' => 'Chichimilá', 'state_id' => 1],
            ['name' => 'Chikindzonot', 'state_id' => 1],
            ['name' => 'Chocholá', 'state_id' => 1],
            ['name' => 'Chumayel', 'state_id' => 1],
            ['name' => 'Conkal', 'state_id' => 1],
            ['name' => 'Cuncunul', 'state_id' => 1],
            ['name' => 'Cuzamá', 'state_id' => 1],
            ['name' => 'Dzemul', 'state_id' => 1],
            ['name' => 'Dzidzantún', 'state_id' => 1],
            ['name' => 'Dzilam de Bravo', 'state_id' => 1],
            ['name' => 'Dzilam González', 'state_id' => 1],
            ['name' => 'Dzitás', 'state_id' => 1],
            ['name' => 'Dzoncauich', 'state_id' => 1],
            ['name' => 'Espita', 'state_id' => 1],
            ['name' => 'Halachó', 'state_id' => 1],
            ['name' => 'Hocabá', 'state_id' => 1],
            ['name' => 'Hoctún', 'state_id' => 1],
            ['name' => 'Homún', 'state_id' => 1],
            ['name' => 'Huhí', 'state_id' => 1],
            ['name' => 'Hunucmá', 'state_id' => 1],
            ['name' => 'Ixil', 'state_id' => 1],
            ['name' => 'Izamal', 'state_id' => 1],
            ['name' => 'Kanasín', 'state_id' => 1],
            ['name' => 'Kantunil', 'state_id' => 1],
            ['name' => 'Kaua', 'state_id' => 1],
            ['name' => 'Kinchil', 'state_id' => 1],
            ['name' => 'Kopomá', 'state_id' => 1],
            ['name' => 'Mama', 'state_id' => 1],
            ['name' => 'Maní', 'state_id' => 1],
            ['name' => 'Maxcanú', 'state_id' => 1],
            ['name' => 'Mayapán', 'state_id' => 1],
            ['name' => 'Mérida', 'state_id' => 1],
            ['name' => 'Mocochá', 'state_id' => 1],
            ['name' => 'Motul', 'state_id' => 1],
            ['name' => 'Muna', 'state_id' => 1],
            ['name' => 'Muxupip', 'state_id' => 1],
            ['name' => 'Opichén', 'state_id' => 1],
            ['name' => 'Oxkutzcab', 'state_id' => 1],
            ['name' => 'Panabá', 'state_id' => 1],
            ['name' => 'Peto', 'state_id' => 1],
            ['name' => 'Progreso', 'state_id' => 1],
            ['name' => 'Quintana Roo', 'state_id' => 1],
            ['name' => 'Río Lagartos', 'state_id' => 1],
            ['name' => 'Sacalum', 'state_id' => 1],
            ['name' => 'Samahil', 'state_id' => 1],
            ['name' => 'Sanahcat', 'state_id' => 1],
            ['name' => 'San Felipe', 'state_id' => 1],
            ['name' => 'Santa Elena', 'state_id' => 1],
            ['name' => 'Seyé', 'state_id' => 1],
            ['name' => 'Sinanché', 'state_id' => 1],
            ['name' => 'Sotuta', 'state_id' => 1],
            ['name' => 'Sucilá', 'state_id' => 1],
            ['name' => 'Sudzal', 'state_id' => 1],
            ['name' => 'Suma', 'state_id' => 1],
            ['name' => 'Tahdziú', 'state_id' => 1],
            ['name' => 'Tahmek', 'state_id' => 1],
            ['name' => 'Teabo', 'state_id' => 1],
            ['name' => 'Tecoh', 'state_id' => 1],
            ['name' => 'Tekal de Venegas', 'state_id' => 1],
            ['name' => 'Tekantó', 'state_id' => 1],
            ['name' => 'Tekax', 'state_id' => 1],
            ['name' => 'Tekit', 'state_id' => 1],
            ['name' => 'Tekom', 'state_id' => 1],
            ['name' => 'Telchac Pueblo', 'state_id' => 1],
            ['name' => 'Telchac Puerto', 'state_id' => 1],
            ['name' => 'Temax', 'state_id' => 1],
            ['name' => 'Temozón', 'state_id' => 1],
            ['name' => 'Tepakán', 'state_id' => 1],
            ['name' => 'Tetiz', 'state_id' => 1],
            ['name' => 'Teya', 'state_id' => 1],
            ['name' => 'Ticul', 'state_id' => 1],
            ['name' => 'Timucuy', 'state_id' => 1],
            ['name' => 'Tinum', 'state_id' => 1],
            ['name' => 'Tixcacalcupul', 'state_id' => 1],
            ['name' => 'Tixkokob', 'state_id' => 1],
            ['name' => 'Tixméhuac', 'state_id' => 1],
            ['name' => 'Tixpéhual', 'state_id' => 1],
            ['name' => 'Tizimín', 'state_id' => 1],
            ['name' => 'Tunkás', 'state_id' => 1],
            ['name' => 'Tzucacab', 'state_id' => 1],
            ['name' => 'Uayma', 'state_id' => 1],
            ['name' => 'Ucú', 'state_id' => 1],
            ['name' => 'Umán', 'state_id' => 1],
            ['name' => 'Valladolid', 'state_id' => 1],
            ['name' => 'Xocchel', 'state_id' => 1],
            ['name' => 'Yaxcabá', 'state_id' => 1],
            ['name' => 'Yaxkukul', 'state_id' => 1],
            ['name' => 'Yobaín', 'state_id' => 1],
        ];
        DB::table('municipalities')->insert($municipalities);
    }
}
